version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly" # default = monday
    open-pull-requests-limit: 30
    target-branch: "main"
    labels:
      - "dependencies"
      - "github"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 30
    labels:
      - "dependencies"
  - package-ecosystem: "docker"
    directory: "/connector"
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 30
    labels:
      - "dependencies"
      
