version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    open-pull-requests-limit: 50
    labels:
      - "dependencies"
      - "github"
  # Gradle
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 50
    labels:
      - "dependencies"
      - "java"
  # NPM
  - package-ecosystem: "npm"
    directory: "/extensions/wrapper/clients/typescript-client-example/"
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 50
    labels:
      - "dependencies"
      - "javascript"
  # NPM
  - package-ecosystem: "npm"
    directory: "/extensions/wrapper/clients/typescript-client/"
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 50
    labels:
      - "dependencies"
      - "javascript"
  # Docker
  - package-ecosystem: "docker"
    directory: "/launchers/"
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 50
    labels:
      - "dependencies"
      - "docker"
