/**
 * EDC REST API
 * EDC REST APIs - merged by OpenApiMerger
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssetRequestDto } from './assetRequestDto';
import { DataAddressDto } from './dataAddressDto';


export interface AssetEntryDto { 
    asset: AssetRequestDto;
    dataAddress: DataAddressDto;
}

