/**
 * EDC REST API
 * EDC REST APIs - merged by OpenApiMerger
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DataPlaneInstance { 
    allowedDestTypes?: Set<string>;
    allowedSourceTypes?: Set<string>;
    id?: string;
    lastActive?: number;
    properties?: { [key: string]: object; };
    turnCount?: number;
    url?: string;
}

