rootProject.name = "edc-extensions"

include(":extensions:contract-agreement-transfer-api")
include(":extensions:edc-ui-config")
include(":extensions:ids-broker-client")
include(":extensions:last-commit-info")
include(":extensions:policy-always-true")
include(":extensions:policy-referring-connector")
include(":extensions:policy-time-interval")
include(":extensions:postgres-flyway")
include(":extensions:sovity-edc-extensions-package")
include(":extensions:wrapper:client")
include(":extensions:wrapper:client-example")
include(":extensions:wrapper:wrapper")
include(":extensions:wrapper:wrapper-broker-api")
include(":extensions:wrapper:wrapper-common-api")
include(":extensions:wrapper:wrapper-ee-api")
include(":connector")
