body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to the discussion! Please fill out this form as completely as possible to help us support you better.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Clearly describe the problem or question you have and what behavior you would have expected.
      placeholder: e.g., "When I try to launch the tool, I receive an error..."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Describe the exact steps you took that led to the final result, so that we can use your input to simulate your situation during our analysis.
      placeholder: |
        1. Set configuration X to '...'
        2. Go to '...'
        3. ...
    validations:
      required: true

  - type: textarea
    id: context_info
    attributes:
      label: Context Information
      description: Provide any relevant context like configuration files (remove sensitive information).
      placeholder: |
        {
          "setting1": "value",
          "setting2": "value"
        }

  - type: textarea
    id: log_output
    attributes:
      label: Relevant log output
      description: Please share relevant logs or error messages with us, ensuring that all sensitive information is removed beforehand.
      placeholder: |
        [Error] Failed to start the application: Connection refused

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots if applicable. Use drag & drop or Markdown image syntax.
      placeholder: Paste image link here or drag a file into the comment editor

  - type: textarea
    id: background_info
    attributes:
      label: Background of your usage
      description: Who are you? What is your affiliation? For what purpose are you using the component (project/phase)? What are your goals?
      placeholder: |
        I'm a developer at Project XYZ using the component as part of an internal tool to achieve...
    validations:
      required: true
