services:
  provider-chat-app-backend:
    build:
      context: ../backend
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "18080:8080"
    environment:
      "chat-app.backend-url-as-reachable-by-own-edc": "http://provider-chat-app-backend:8080"
      "chat-app.edc.connector-endpoint": "http://provider/api/dsp"
      "chat-app.edc.management-api.url": "http://provider/api/management"
      "chat-app.edc.management-api.key": "SomeOtherApiKey"

  provider-chat-app-frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "13000:3000"
    environment:
      NEXT_PUBLIC_USE_FAKE_BACKEND: "false"
      NEXT_PUBLIC_BACKEND_URL: "http://localhost:18080/api/ui"

  consumer-chat-app-backend:
    build:
      context: ../backend
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "28080:8080"
    environment:
      "chat-app.backend-url-as-reachable-by-own-edc": "http://consumer-chat-app-backend:8080"
      "chat-app.edc.connector-endpoint": "http://consumer/api/dsp"
      "chat-app.edc.management-api.url": "http://consumer/api/management"
      "chat-app.edc.management-api.key": "SomeOtherApiKey"

  consumer-chat-app-frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "23000:3000"
    environment:
      NEXT_PUBLIC_USE_FAKE_BACKEND: "false"
      NEXT_PUBLIC_BACKEND_URL: "http://localhost:28080/api/ui"
