blank_issues_enabled: true
contact_links:
  - name: Security vulnerabilities
    url: https://github.com/sovity/edc-extensions/security/policy
    about: If you want to report a security issue, please contact us directly.
