/**
 * EDC REST API
 * All files merged by open api merger
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContractOffer } from './contractOffer';


export interface ContractOfferRequest { 
    type?: ContractOfferRequest.TypeEnum;
    protocol?: string;
    connectorId?: string;
    connectorAddress?: string;
    correlationId?: string;
    contractOffer?: ContractOffer;
}
export namespace ContractOfferRequest {
    export type TypeEnum = 'INITIAL' | 'COUNTER_OFFER';
    export const TypeEnum = {
        Initial: 'INITIAL' as TypeEnum,
        CounterOffer: 'COUNTER_OFFER' as TypeEnum
    };
}


