/**
 * EDC REST API
 * All files merged by open api merger
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataAddress } from './dataAddress';


export interface DataFlowRequest { 
    destinationDataAddress?: DataAddress;
    id?: string;
    processId?: string;
    properties?: { [key: string]: string; };
    sourceDataAddress?: DataAddress;
    traceContext?: { [key: string]: string; };
    trackable?: boolean;
}

