/**
 * EDC REST API
 * All files merged by open api merger
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataRequestDto } from './dataRequestDto';
import { DataAddressInformationDto } from './dataAddressInformationDto';


export interface TransferProcessDto {
    id: string;
    state: string;
    type: string;
    errorDetail?: string;
    dataRequest: DataRequestDto;
    dataDestination?: DataAddressInformationDto;
    stateTimestamp?: number;
    createdTimestamp?: number;
}

