/**
 * EDC REST API
 * All files merged by open api merger
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {DataRequestDto} from './dataRequestDto';
import {DataAddressInformationDto} from './dataAddressInformationDto';


export interface TransferProcessDto {
  id: string;
  type: string;
  state: string;
  errorDetail?: string;
  dataRequest: DataRequestDto;
  dataDestination?: DataAddressInformationDto;
  createdTimestamp?: number; // epoch millis
  stateTimestamp?: number; // epoch millis
}

