name: Add issue to project action

on:
  issues:
    types:
      - opened

jobs:
  add_issue_to_project:
    if: "!(startsWith(github.event.issue.title, '[Zammad Ticket') && github.event.issue.user.login == 'sovitybot')"
    name: add_issue_to_project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/sovity/projects/9
          github-token: ${{ secrets.ADD_ISSUE_TO_PROJECT_PAT }}
