name: Documentation Checks

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]
  pull_request:
    branches: [ main ]

jobs:
  markdown-link-checks:
    name: Markdown Link Checks
    runs-on: ubuntu-latest
    steps:
      - uses: FranzDiebold/github-env-vars-action@v2
      - uses: actions/checkout@master
      - name: "Markdown Link Checker: Generate Config"
        run: .github/markdown-link-checker-config.jq > .github/markdown-link-checker-config.json
      - name: "Markdown Link Checker: Validate Links"
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          config-file: '.github/markdown-link-checker-config.json'
