name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  release:
    types: [published]
  pull_request:
    branches: [main]

env:
  REGISTRY_URL: ghcr.io
  REGISTRY_USER: ${{ github.actor }}
  IMAGE_BASE_NAME: ${{ github.repository_owner }}

jobs:
  build-connector-image-ce:
    name: Build CE Connector Image
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: "Set up JDK 21"
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3.14.1
        with:
          java-version: "21"
          distribution: "temurin"
      - name: "Gradle: Validate Gradle Wrapper"
        uses: gradle/actions/wrapper-validation@ed408507eac070d1f99cc633dbcf757c94c7933a # v4.4.3
      - name: "Gradle: Set up Gradle"
        uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3.5.0
      - name: "Gradle: Build"
        working-directory: connector
        env:
          USERNAME: ${{ env.REGISTRY_USER }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build -x test ${{ env.GRADLE_ARGS }}
      - name: "Docker Image: edc-ce"
        uses: ./.github/actions/build-connector-image
        with:
          registry-url: ${{ env.REGISTRY_URL }}
          registry-user: ${{ env.REGISTRY_USER }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          image-base-name: ${{ env.IMAGE_BASE_NAME }}
          image-name: "edc-ce"
          image-title: "sovity Community Edition EDC Connector"
          image-description: "Eclipse EDC Connector built by sovity. This image supports multiple data spaces and contains multiple kinds of deployments: Standalone Control Plane, Standalone Dataplane, Combined Control and Dataplane"
          connector-dir: "connector/ce/docker-image-ce"
  build-connector-ui-image-ce:
    name: Build CE Connector UI Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: "Set up Node 24"
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: "24.x"
          cache: "yarn"
          cache-dependency-path: |
            frontend/yarn.lock
      - name: "Docker Image: edc-ce-ui"
        uses: ./.github/actions/build-connector-ui-image
        with:
          registry-url: ${{ env.REGISTRY_URL }}
          registry-user: ${{ env.REGISTRY_USER }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          image-base-name: ${{ env.IMAGE_BASE_NAME }}
          image-name: "edc-ce-ui"
          image-title: "sovity EDC CE UI"
          image-description: "UI for the sovity EDC CE Connector"
          connector-ui-dir: "frontend"
  run-connector-tests-ce:
    name: Run CE Gradle Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: "Set up JDK 21"
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3.14.1
        with:
          java-version: "21"
          distribution: "temurin"
      - name: "Gradle: Validate Gradle Wrapper"
        uses: gradle/actions/wrapper-validation@ed408507eac070d1f99cc633dbcf757c94c7933a # v4.4.3
      - name: "Gradle: Set up Gradle"
        uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3.5.0
      - name: "Gradle: Test"
        working-directory: connector
        env:
          USERNAME: ${{ env.REGISTRY_USER }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew test -x :ce:docker-image-ce:assemble
  publish-jars-ce:
    name: Publish CE Jars
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: "Set up JDK 21"
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3.14.1
        with:
          java-version: "21"
          distribution: "temurin"
      - name: "Gradle: Validate Gradle Wrapper"
        uses: gradle/actions/wrapper-validation@ed408507eac070d1f99cc633dbcf757c94c7933a # v4.4.3
        env:
          USERNAME: ${{ env.REGISTRY_USER }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Gradle: Overwrite Artifact Version (Release Only)"
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          GRADLE_ARGS="-Pversion=${GITHUB_REF#refs/tags/v}"
          echo "GRADLE_ARGS=$GRADLE_ARGS" >> $GITHUB_ENV
      - name: "Gradle: Set up Gradle"
        uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3.5.0
      - name: "Gradle: Publish (Release Only)"
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        working-directory: connector
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish -x test -x :ce:docker-image-ce:assemble ${{ env.GRADLE_ARGS }}
  build-client-library-typescript:
    name: TS API Client Library
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: "Set up JDK 21"
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3.14.1
        with:
          java-version: "21"
          distribution: "temurin"
      - name: "Set up Node 24"
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
          cache-dependency-path: connector/ce/libs/api-clients/typescript-client/package.json
      - name: "Gradle: Validate Gradle Wrapper"
        uses: gradle/actions/wrapper-validation@ed408507eac070d1f99cc633dbcf757c94c7933a # v4.4.3
      - name: "Gradle: Set up Gradle"
        uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3.5.0
      - name: "Gradle: Generate TS Code"
        working-directory: connector
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew :ce:libs:api-clients:typescript-client:openApiGenerate -x test
      - name: "NPM: Dist Tag & Version"
        working-directory: ./connector/ce/libs/api-clients/typescript-client
        run: |
          if [[ "$GITHUB_REF" == "refs/tags/v"* ]]; then
            # Full Release
            VERSION="${GITHUB_REF#refs/tags/v}"
            DIST_TAG=latest
          else
            VERSION="0.$(date '+%Y%m%d.%H%M%S')-main-${GITHUB_SHA::8}"
            DIST_TAG=main
          fi
          npm version $VERSION
          echo "DIST_TAG=$DIST_TAG" >> $GITHUB_ENV
      - name: "NPM: Build"
        working-directory: connector/ce/libs/api-clients/typescript-client
        run: npm ci && npm run build
      - name: "NPM: Publish (Main & Releases Only)"
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') }}
        working-directory: connector/ce/libs/api-clients/typescript-client
        run: npm publish --access public --tag "${{ env.DIST_TAG }}"
  check-migration-script-names:
    name: "Check Migration Script Names"
    env:
      MIGRATIONS_DIR_CE: connector/ce/utils/db-schema-ce/src/main/resources/db/migration-ce
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Validate CE Migration Scripts
        run: |
          function check_migrations_dir () {
            MIGRATIONS_DIR=$1
            PATTERN=$2

            FILES=$(ls -A "$MIGRATIONS_DIR")

            if [[ ! (-d "$1" && -n $FILES) ]]; then
              echo "Error: Directory either doesn't exist or is empty" >&2
              exit 1
            fi

            echo "Checking $MIGRATIONS_DIR"

            for filename in $FILES ; do
              if [[ ! "$filename" =~ $PATTERN ]]; then
                echo "Error: Invalid migration script name: ${filename##*/}"
                echo "Expected format: $PATTERN"
                exit 1
              fi
              echo "✓ ${filename}"
            done

            echo "✓ All migration scripts follow $PATTERN"
          }

          MIGRATION_DIR_CE='connector/ce/utils/db-schema-ce/src/main/resources/db/migration-ce'

          PATTERN_CE='^V([0-9]+\.[0-9]+\.[0-9]+)__Release_\1_CE\.sql$'

          if [[ ! "${{ github.ref }}" =~ '^refs/tags/v' ]] && [[ ! "${{ github.event.pull_request.head.ref }}" == "next" ]]; then
            PATTERN_CE+='|^V99__Unreleased_CE.sql$'
          fi

          echo "Checking CE Migrations"
          check_migrations_dir "$MIGRATION_DIR_CE" "$PATTERN_CE"

  ci_status:
    if: always()
    name: CI Status

    needs:
      - build-connector-image-ce
      - build-connector-ui-image-ce
      - publish-jars-ce
      - run-connector-tests-ce
      - build-client-library-typescript
      - check-migration-script-names

    runs-on: ubuntu-latest

    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
